 INSERT INTO 'transport' VALUES ('1', 'Πούλμαν', 'A0');
 INSERT INTO 'transport' VALUES ('2', 'Μετρό', 'Γ1');
 INSERT INTO 'transport' VALUES ('3', 'Μετρό', 'Γ2');
 INSERT INTO 'transport' VALUES ('4', 'Πούλμαν', 'A3');
 INSERT INTO 'transport' VALUES ('5', 'Πούλμαν', 'A4');
 INSERT INTO 'transport' VALUES ('6', 'Μετρό', 'Γ5');
 INSERT INTO 'transport' VALUES ('7', 'Πούλμαν', 'A0');
 INSERT INTO 'transport' VALUES ('8', 'Μετρό', 'Γ6');
 INSERT INTO 'transport' VALUES ('9', 'Μετρό', 'Γ7');
 INSERT INTO 'transport' VALUES ('10', 'Πούλμαν', 'A2');
 INSERT INTO 'transport' VALUES ('11', 'Πούλμαν', 'A5');
 INSERT INTO 'transport' VALUES ('12', 'Μετρό', 'Γ8');
 INSERT INTO 'transport' VALUES ('13', 'Μετρό', 'Γ5');
 INSERT INTO 'transport' VALUES ('14', 'Πούλμαν', 'A0');
 INSERT INTO 'transport' VALUES ('15', 'Μετρό', 'Γ6');
 INSERT INTO 'transport' VALUES ('16', 'Μετρό', 'Γ7');
 INSERT INTO 'transport' VALUES ('17', 'Πούλμαν', 'A2');
 INSERT INTO 'transport' VALUES ('18', 'Πούλμαν', 'A5');
 INSERT INTO 'transport' VALUES ('19', 'Μετρό', 'Γ8');
 INSERT INTO 'transport' VALUES ('20', 'Πούλμαν', 'A5');
 INSERT INTO 'transport' VALUES ('21', 'Μετρό', 'Γ8');


 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('1', 'Βαλσαμάτα');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('2', 'Γριζάτα');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('3', 'Ζόλα');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('3', 'Διλινάτα');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('4', 'Διλινάτα');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('4', 'Γριζάτα');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('4', 'Αγία Ειρήνη');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('5', 'Αγία Ειρήνη');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('6', 'Καμιναράτα');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('7', 'Μιτικάτα');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('8', 'Μακρυώτικα');
 INSERT OR REPLACE INTO 'Cov_locations' VALUES ('8', 'Τζανάτα');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('9',  'Τζανάτα');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('10', 'Φαρακλάτα');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('10', 'Φαρακλάτα');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('10', 'Περιστέρι');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('10', 'Άδαμας');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('10', 'Πλάκα');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('11', 'Πλάκα');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('12', 'Άδαμας');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('13', 'Περιστέρι');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('14', 'Χαλάνδρι');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('15', 'Κηφισιά');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('16', 'Γλυφάδα');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('17', 'Πειραιάς');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('18', 'Αγυιά');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('19', 'Κέντρο');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('20', 'Φάληρο');
  INSERT OR REPLACE INTO 'Cov_locations' VALUES ('21', 'Φώκι');